### PR TITLE
Bugfix: remove if false and fix full path

### PR DESCRIPTION
**Pull request by vitormattos**
Removed `if(false)` and fix wrong path when I change file in mapped (shared) folder

How to reproduce?

* Loggin using user A
* create a user called B
* create a folder called test using user B
* put a file with name example.csv to run the workflow script into folder test
* goto settings and create a script flow with this settings:
    * file name: /^example.csv$/
    * script: "ls %f"
* using user B, share the test folder to user A
* with user A, change the file inside test folder
* look the jobs in database to find the command

You will find in place of %f this text: "/var/www/html/data/B/test/B/test/example.csv" you need see "/var/www/html/data/B/test/example.csv"

### CODE REVIEW

**Comment by phreaker0** [comment]
tested this patch and works for me on v20.0.4, thx

**Review by blizzz — APPROVED** [review]
thanks! :)

**Pull request merged**
