### PR TITLE
Remove non-exsting main branch from workflow

### PR DESCRIPTION
**Pull request by come-nc**
Avoid failure for main in https://github.com/nextcloud/workflow_script/actions/runs/5703841231

### CODE REVIEW

**Comment by nickvergessen** [comment]
Kind of useless, the next workflow sync will bring it back. So let's just keep it avoid confusion on workflow template updates.

**Comment by come-nc** [comment]
> Kind of useless, the next workflow sync will bring it back. So let's just keep it avoid confusion on workflow template updates.

Can we fix the workflow to not fail when the branch is missing then? I get an email each time this fails.

**Comment by nickvergessen** [comment]
> Can we fix the workflow to not fail when the branch is missing then?

Sure

> I get an email each time this fails.

How can I get that? :)

**Comment by come-nc** [comment]
> > Can we fix the workflow to not fail when the branch is missing then?
> 
> Sure
> 
> > I get an email each time this fails.
> 
> How can I get that? :)

Like this I suppose
Screenshot_20230731_164354

**Comment by nickvergessen** [comment]
Ah, it's on https://github.com/settings/notifications 

Nice :)

So yeah, let's make it non-failing in the workflow template and then spill it over

**Pull request closed without merging**
